# Generated by Django 5.1.6 on 2025-02-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_image_alter_galleryimage_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('count', models.PositiveIntegerField(default=0)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
